# -*- coding: utf-8 -*-
"""SE-RRM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2xYTpxiIRGf-YCChnq_TGrNNHfw7PlU
"""

!pip -q install torch torchvision torchaudio
!pip -q install transformers
!pip -q install einops
!pip -q install tqdm
!pip -q install matplotlib
!pip -q install seaborn
!pip -q install pandas
!pip -q install numpy
!pip -q install scikit-learn
!pip -q install python-sat[pblib,aiger]
!pip -q install gradio
!pip -q install requests

import os
import json
import time
import random
import math
import requests

import numpy as np
import pandas as pd

from tqdm import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

from sklearn.model_selection import train_test_split

from einops import rearrange

from pysat.solvers import Glucose4

print("Torch Version :", torch.__version__)

print("CUDA Available :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SEED = 42

BOARD_SIZE = 9

NUM_CLASSES = 9

BATCH_SIZE = 128

EPOCHS = 10

LEARNING_RATE = 1e-3

MODEL_DIM = 256

NUM_HEADS = 8

NUM_LAYERS = 4

SAVE_DIR = "models"

DATA_DIR = "data"

print(DEVICE)

def seed_everything(seed=42):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True

    torch.backends.cudnn.benchmark = False


seed_everything(SEED)

print("Random seed fixed.")

folders = [

    "data",

    "models",

    "plots",

    "solver",

    "dataset",

    "checkpoints",

    "results",

    "notebooks"

]

for folder in folders:

    os.makedirs(folder, exist_ok=True)

print("Folders created.")

OPENROUTER_API_KEY = "YOUR_API_KEY"

OPENROUTER_MODEL = "openrouter/free"

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

class Timer:

    def __enter__(self):

        self.start = time.time()

        return self

    def __exit__(self, *args):

        self.end = time.time()

        self.interval = self.end - self.start

with Timer() as t:

    x = sum(range(1000000))

print(t.interval)

def save_model(model, path):

    torch.save(model.state_dict(), path)

    print("Saved:", path)


def load_model(model, path):

    model.load_state_dict(torch.load(path, map_location=DEVICE))

    model.eval()

    print("Loaded:", path)

sns.set_style("darkgrid")

plt.rcParams["figure.figsize"] = (10,6)

plt.rcParams["font.size"] = 12

print("=" * 50)

print("DEVICE:", DEVICE)

print("Torch:", torch.__version__)

print("NumPy:", np.__version__)

print("Pandas:", pd.__version__)

print("=" * 50)

EMPTY = 0

DIGITS = list(range(1, 10))

def print_board(board):

    for r in range(9):

        if r % 3 == 0 and r != 0:
            print("-" * 25)

        row = ""

        for c in range(9):

            if c % 3 == 0 and c != 0:
                row += "| "

            value = board[r][c]

            if value == 0:
                row += ". "
            else:
                row += str(value) + " "

        print(row)

board = np.zeros((9,9), dtype=int)

print_board(board)

def valid(board, row, col, num):

    # Row
    if num in board[row]:
        return False

    # Column
    if num in board[:, col]:
        return False

    # Box
    box_row = (row // 3) * 3
    box_col = (col // 3) * 3

    for r in range(box_row, box_row + 3):
        for c in range(box_col, box_col + 3):

            if board[r][c] == num:
                return False

    return True

def find_empty(board):

    for r in range(9):
        for c in range(9):

            if board[r][c] == 0:
                return r, c

    return None

def fill_board(board):

    empty = find_empty(board)

    if empty is None:
        return True

    row, col = empty

    numbers = list(range(1, 10))
    random.shuffle(numbers)

    for num in numbers:

        if valid(board, row, col, num):

            board[row][col] = num

            if fill_board(board):
                return True

            board[row][col] = 0

    return False

def generate_solution():

    board = np.zeros((9,9), dtype=np.int32)

    fill_board(board)

    return board

solution = generate_solution()

print_board(solution)

def create_puzzle(solution, clues=35):

    puzzle = solution.copy()

    cells = [(r, c) for r in range(9) for c in range(9)]

    random.shuffle(cells)

    remove = 81 - clues

    for i in range(remove):

        r, c = cells[i]

        puzzle[r][c] = 0

    return puzzle

solution = generate_solution()

puzzle = create_puzzle(solution, clues=35)

print("Puzzle")

print_board(puzzle)

print()

print("Solution")

print_board(solution)

def empty_cells(board):

    return np.sum(board == 0)

print(empty_cells(puzzle))

def verify(board):

    target = set(range(1,10))

    # rows
    for row in board:
        if set(row) != target:
            return False

    # columns
    for col in board.T:
        if set(col) != target:
            return False

    # boxes
    for br in range(3):
        for bc in range(3):

            block = board[
                br*3:(br+1)*3,
                bc*3:(bc+1)*3
            ].flatten()

            if set(block) != target:
                return False

    return True

print(verify(solution))

DIFFICULTY = {

    "easy": 40,

    "medium": 34,

    "hard": 28,

    "expert": 24

}

solution = generate_solution()

puzzle = create_puzzle(solution, DIFFICULTY["hard"])

print_board(puzzle)

def save_puzzle(puzzle, solution, filename):

    np.savez(

        filename,

        puzzle=puzzle,

        solution=solution

    )

save_puzzle(

    puzzle,

    solution,

    "data/example.npz"

)

def load_puzzle(filename):

    data = np.load(filename)

    return data["puzzle"], data["solution"]

p, s = load_puzzle("data/example.npz")

print_board(p)

NUM_SAMPLES = 100

for i in tqdm(range(NUM_SAMPLES)):

    solution = generate_solution()

    puzzle = create_puzzle(solution, clues=35)

    save_puzzle(

        puzzle,

        solution,

        f"data/{i:05d}.npz"

    )

print("Done!")

files = sorted(os.listdir("data"))

print("Total puzzles:", len(files))

p, s = load_puzzle(os.path.join("data", files[0]))

print()

print("Puzzle")

print_board(p)

print()

print("Solution")

print_board(s)

print()

print("Verified:", verify(s))

def solve(board):

    empty = find_empty(board)

    if empty is None:
        return True

    row, col = empty

    for num in range(1,10):

        if valid(board,row,col,num):

            board[row][col]=num

            if solve(board):
                return True

            board[row][col]=0

    return False

def count_solutions(board, limit=2):

    empty = find_empty(board)

    if empty is None:
        return 1

    row,col = empty

    total = 0

    for num in range(1,10):

        if valid(board,row,col,num):

            board[row,col]=num

            total += count_solutions(board,limit)

            board[row,col]=0

            if total >= limit:
                break

    return total

def create_unique_puzzle(solution, clues=35):

    puzzle = solution.copy()

    cells = [(r,c) for r in range(9)
                    for c in range(9)]

    random.shuffle(cells)

    remove = 81-clues

    removed = 0

    for r,c in cells:

        backup = puzzle[r,c]

        puzzle[r,c]=0

        test = puzzle.copy()

        n = count_solutions(test)

        if n != 1:

            puzzle[r,c]=backup

        else:

            removed += 1

        if removed == remove:
            break

    return puzzle

solution = generate_solution()

puzzle = create_unique_puzzle(solution,35)

print_board(puzzle)

print()

tmp = puzzle.copy()

print("Solutions:",count_solutions(tmp))

DIFFICULTY = {

    "easy":40,

    "medium":34,

    "hard":28,

    "expert":24

}

NUM_DATA = 5000

os.makedirs("data",exist_ok=True)

for i in tqdm(range(NUM_DATA)):

    solution = generate_solution()

    puzzle = create_unique_puzzle(

        solution,

        clues=35

    )

    np.savez(

        f"data/{i:05d}.npz",

        puzzle=puzzle,

        solution=solution

    )

print("Finished.")

class SudokuDataset(Dataset):

    def __init__(self,folder):

        self.files = sorted(

            os.listdir(folder)

        )

        self.folder = folder

    def __len__(self):

        return len(self.files)

    def __getitem__(self,index):

        data = np.load(

            os.path.join(

                self.folder,

                self.files[index]

            )

        )

        puzzle = data["puzzle"]

        solution = data["solution"]

        x = torch.tensor(

            puzzle.flatten(),

            dtype=torch.long

        )

        y = torch.tensor(

            solution.flatten()-1,

            dtype=torch.long

        )

        return x,y

dataset = SudokuDataset("data")

indices = list(range(len(dataset)))

train_idx, val_idx = train_test_split(

    indices,

    test_size=0.1,

    random_state=42

)

from torch.utils.data import Subset

train_dataset = Subset(

    dataset,

    train_idx

)

val_dataset = Subset(

    dataset,

    val_idx

)

train_loader = DataLoader(

    train_dataset,

    batch_size=128,

    shuffle=True,

    num_workers=2,

    pin_memory=True

)

val_loader = DataLoader(

    val_dataset,

    batch_size=128,

    shuffle=False,

    num_workers=2,

    pin_memory=True

)

x,y = next(iter(train_loader))

print(x.shape)

print(y.shape)

board = x[0].reshape(9,9).numpy()

solution = (y[0]+1).reshape(9,9).numpy()

print("Puzzle")

print_board(board)

print()

print("Solution")

print_board(solution)

VOCAB_SIZE = 10          # 0-9 (0 = empty)

EMBED_DIM = 256

NUM_HEADS = 8

HIDDEN_DIM = 512

REASONING_STEPS = 8

DROPOUT = 0.1

NUM_CLASSES = 9

SEQ_LEN = 81

class SudokuEmbedding(nn.Module):

    def __init__(self):

        super().__init__()

        self.token_embedding = nn.Embedding(
            VOCAB_SIZE,
            EMBED_DIM
        )

        self.position_embedding = nn.Parameter(
            torch.randn(
                1,
                SEQ_LEN,
                EMBED_DIM
            )
        )

    def forward(self,x):

        token = self.token_embedding(x)

        return token + self.position_embedding

class FeedForward(nn.Module):

    def __init__(self):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(
                EMBED_DIM,
                HIDDEN_DIM
            ),

            nn.GELU(),

            nn.Dropout(DROPOUT),

            nn.Linear(
                HIDDEN_DIM,
                EMBED_DIM
            )

        )

    def forward(self,x):

        return self.net(x)

class AttentionBlock(nn.Module):

    def __init__(self):

        super().__init__()

        self.norm = nn.LayerNorm(
            EMBED_DIM
        )

        self.attn = nn.MultiheadAttention(

            embed_dim=EMBED_DIM,

            num_heads=NUM_HEADS,

            dropout=DROPOUT,

            batch_first=True

        )

    def forward(self,x):

        y = self.norm(x)

        out,_ = self.attn(

            y,

            y,

            y,

            need_weights=False

        )

        return x + out

class FFNBlock(nn.Module):

    def __init__(self):

        super().__init__()

        self.norm = nn.LayerNorm(

            EMBED_DIM

        )

        self.ff = FeedForward()

    def forward(self,x):

        return x + self.ff(

            self.norm(x)

        )

class ReasoningBlock(nn.Module):

    def __init__(self):

        super().__init__()

        self.attn = AttentionBlock()

        self.ffn = FFNBlock()

    def forward(self,x):

        x = self.attn(x)

        x = self.ffn(x)

        return x

class RecurrentReasoner(nn.Module):

    def __init__(self):

        super().__init__()

        self.block = ReasoningBlock()

    def forward(

        self,

        x,

        steps=REASONING_STEPS

    ):

        for _ in range(steps):

            x = self.block(x)

        return x

class PredictionHead(nn.Module):

    def __init__(self):

        super().__init__()

        self.norm = nn.LayerNorm(

            EMBED_DIM

        )

        self.linear = nn.Linear(

            EMBED_DIM,

            NUM_CLASSES

        )

    def forward(self,x):

        x = self.norm(x)

        return self.linear(x)

class SudokuRRM(nn.Module):

    def __init__(self):

        super().__init__()

        self.embedding = SudokuEmbedding()

        self.reasoner = RecurrentReasoner()

        self.head = PredictionHead()

    def forward(self,x):

        x = self.embedding(x)

        x = self.reasoner(x)

        logits = self.head(x)

        return logits

model = SudokuRRM().to(DEVICE)

total = sum(

    p.numel()

    for p in model.parameters()

)

trainable = sum(

    p.numel()

    for p in model.parameters()

    if p.requires_grad

)

print(model)

print()

print(f"Parameters : {total:,}")

print(f"Trainable : {trainable:,}")

def initialize_weights(model):

    for m in model.modules():

        if isinstance(m, nn.Linear):

            nn.init.xavier_uniform_(m.weight)

            if m.bias is not None:
                nn.init.zeros_(m.bias)

        elif isinstance(m, nn.Embedding):

            nn.init.normal_(

                m.weight,

                mean=0.0,

                std=0.02

            )

        elif isinstance(m, nn.LayerNorm):

            nn.init.ones_(m.weight)

            nn.init.zeros_(m.bias)


initialize_weights(model)

print("Weights initialized.")

criterion = nn.CrossEntropyLoss(
    reduction="none"
)

def masked_loss(

    logits,

    target,

    puzzle

):

    B = logits.shape[0]

    logits = logits.reshape(

        B*81,

        9

    )

    target = target.reshape(

        B*81

    )

    puzzle = puzzle.reshape(

        B*81

    )

    losses = criterion(

        logits,

        target

    )

    mask = (

        puzzle == 0

    ).float()

    loss = (

        losses * mask

    ).sum() / (

        mask.sum() + 1e-8

    )

    return loss

optimizer = torch.optim.AdamW(

    model.parameters(),

    lr=LEARNING_RATE,

    weight_decay=1e-4

)

print(optimizer)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(

    optimizer,

    T_max=EPOCHS

)

scaler = torch.cuda.amp.GradScaler()

print("AMP Ready")

def masked_accuracy(

    logits,

    target,

    puzzle

):

    pred = logits.argmax(-1)

    mask = puzzle == 0

    correct = (

        pred == target

    ) & mask

    acc = (

        correct.sum().float()

        /

        (mask.sum()+1e-8)

    )

    return acc.item()

@torch.no_grad()

def predict_probabilities(

    board

):

    model.eval()

    x = torch.tensor(

        board.flatten(),

        dtype=torch.long

    ).unsqueeze(0)

    x = x.to(DEVICE)

    logits = model(x)

    probs = torch.softmax(

        logits,

        dim=-1

    )

    return probs.squeeze(0).cpu().numpy()

@torch.no_grad()

def predict_board(

    board

):

    probs = predict_probabilities(

        board

    )

    pred = np.argmax(

        probs,

        axis=1

    ) + 1

    return pred.reshape(

        9,

        9

    )

def rank_digits(

    probabilities

):

    ranking = np.argsort(

        probabilities

    )[::-1]

    return ranking + 1

x = torch.randint(

    0,

    10,

    (2,81)

).to(DEVICE)

with torch.no_grad():

    y = model(x)

print(

    "Input :",x.shape

)

print(

    "Output:",y.shape

)

history = {

    "train_loss": [],

    "val_loss": [],

    "train_acc": [],

    "val_acc": []

}

def train_one_epoch(model, loader):

    model.train()

    running_loss = 0.0

    running_acc = 0.0

    for puzzle, target in tqdm(loader):

        puzzle = puzzle.to(DEVICE)

        target = target.to(DEVICE)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast():

            logits = model(puzzle)

            loss = masked_loss(

                logits,

                target,

                puzzle

            )

        scaler.scale(loss).backward()

        scaler.step(optimizer)

        scaler.update()

        acc = masked_accuracy(

            logits,

            target,

            puzzle

        )

        running_loss += loss.item()

        running_acc += acc

    return (

        running_loss / len(loader),

        running_acc / len(loader)

    )

@torch.no_grad()

def validate(model, loader):

    model.eval()

    running_loss = 0

    running_acc = 0

    for puzzle, target in loader:

        puzzle = puzzle.to(DEVICE)

        target = target.to(DEVICE)

        logits = model(puzzle)

        loss = masked_loss(

            logits,

            target,

            puzzle

        )

        acc = masked_accuracy(

            logits,

            target,

            puzzle

        )

        running_loss += loss.item()

        running_acc += acc

    return (

        running_loss / len(loader),

        running_acc / len(loader)

    )

def save_checkpoint(

    epoch,

    model,

    optimizer,

    history,

    filename

):

    torch.save(

        {

            "epoch": epoch,

            "model": model.state_dict(),

            "optimizer": optimizer.state_dict(),

            "history": history

        },

        filename

    )

    print("Saved", filename)

def load_checkpoint(filename):

    ckpt = torch.load(

        filename,

        map_location=DEVICE

    )

    model.load_state_dict(

        ckpt["model"]

    )

    optimizer.load_state_dict(

        ckpt["optimizer"]

    )

    print("Loaded")

    return ckpt["epoch"]

best_loss = float("inf")

patience = 5

counter = 0

for epoch in range(EPOCHS):

    print()

    print("="*60)

    print(

        "Epoch",

        epoch+1,

        "/",

        EPOCHS

    )

    train_loss, train_acc = train_one_epoch(

        model,

        train_loader

    )

    val_loss, val_acc = validate(

        model,

        val_loader

    )

    scheduler.step()

    history["train_loss"].append(train_loss)

    history["val_loss"].append(val_loss)

    history["train_acc"].append(train_acc)

    history["val_acc"].append(val_acc)

    print(

        f"Train Loss : {train_loss:.4f}"

    )

    print(

        f"Train Acc  : {train_acc:.4f}"

    )

    print(

        f"Val Loss   : {val_loss:.4f}"

    )

    print(

        f"Val Acc    : {val_acc:.4f}"

    )

    if val_loss < best_loss:

        best_loss = val_loss

        counter = 0

        save_checkpoint(

            epoch,

            model,

            optimizer,

            history,

            "checkpoints/best.pt"

        )

    else:

        counter += 1

        print(

            "Patience",

            counter,

            "/",

            patience

        )

        if counter >= patience:

            print(

                "Early stopping."

            )

            break

plt.figure(figsize=(8,5))

plt.plot(

    history["train_loss"],

    label="Train"

)

plt.plot(

    history["val_loss"],

    label="Validation"

)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(

    history["train_acc"],

    label="Train"

)

plt.plot(

    history["val_acc"],

    label="Validation"

)

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.show()

model.eval()

sample, target = dataset[0]

board = sample.reshape(9,9).numpy()

prediction = predict_board(board)

print("Puzzle")

print_board(board)

print()

print("Prediction")

print_board(prediction)

print()

print("Ground Truth")

print_board(

    (target+1).reshape(9,9).numpy()

)

class SudokuRRM(nn.Module):

    def __init__(self):

        super().__init__()

        self.embedding = SudokuEmbedding()

        self.reasoner = RecurrentReasoner()

        self.head = PredictionHead()

    def forward(self, x, return_all=False):

        x = self.embedding(x)

        outputs = []

        for _ in range(REASONING_STEPS):

            x = self.reasoner.block(x)

            logits = self.head(x)

            outputs.append(logits)

        if return_all:

            return outputs

        return outputs[-1]

def multi_step_loss(outputs, target, puzzle, weights=None):

    if weights is None:

        weights = torch.linspace(0.3, 1.0, len(outputs)).to(DEVICE)

    total_loss = 0

    for i, logits in enumerate(outputs):

        loss = masked_loss(logits, target, puzzle)

        total_loss += weights[i] * loss

    return total_loss / weights.sum()

def train_one_epoch(model, loader):

    model.train()

    total_loss = 0

    total_acc = 0

    for puzzle, target in tqdm(loader):

        puzzle = puzzle.to(DEVICE)

        target = target.to(DEVICE)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast():

            outputs = model(puzzle, return_all=True)

            loss = multi_step_loss(outputs, target, puzzle)

        scaler.scale(loss).backward()

        scaler.step(optimizer)

        scaler.update()

        logits = outputs[-1]

        acc = masked_accuracy(logits, target, puzzle)

        total_loss += loss.item()

        total_acc += acc

    return (

        total_loss / len(loader),

        total_acc / len(loader)

    )

@torch.no_grad()

def validate(model, loader):

    model.eval()

    total_loss = 0

    total_acc = 0

    for puzzle, target in loader:

        puzzle = puzzle.to(DEVICE)

        target = target.to(DEVICE)

        outputs = model(puzzle, return_all=True)

        loss = multi_step_loss(outputs, target, puzzle)

        logits = outputs[-1]

        acc = masked_accuracy(logits, target, puzzle)

        total_loss += loss.item()

        total_acc += acc

    return (

        total_loss / len(loader),

        total_acc / len(loader)

    )

model = SudokuRRM().to(DEVICE)
print("Model reinitialized with new forward()")

import inspect

print(inspect.signature(model.forward))

model.eval()

sample, target = dataset[0]

sample = sample.unsqueeze(0).to(DEVICE)

outputs = model(sample, return_all=True)

print("Steps:", len(outputs))

for i, out in enumerate(outputs):
    print(i+1, out.shape)

def is_valid(board, row, col, num):

    # row check
    if num in board[row]:
        return False

    # column check
    if num in board[:, col]:
        return False

    # 3x3 box check
    r0 = (row // 3) * 3
    c0 = (col // 3) * 3

    if num in board[r0:r0+3, c0:c0+3]:
        return False

    return True

def find_empty(board):

    for r in range(9):

        for c in range(9):

            if board[r][c] == 0:

                return r, c

    return None

class Stats:

    def __init__(self):

        self.nodes = 0

        self.backtracks = 0

def solve_backtracking(board, stats):

    stats.nodes += 1

    empty = find_empty(board)

    if empty is None:

        return True

    row, col = empty

    for num in range(1, 10):

        if is_valid(board, row, col, num):

            board[row][col] = num

            if solve_backtracking(board, stats):

                return True

            board[row][col] = 0

            stats.backtracks += 1

    return False

puzzle, solution = dataset[0]

stats = Stats()

board = puzzle.detach().cpu().numpy().copy()

# 🔥 IMPORTANT: reshape to 9×9
board = board.reshape(9, 9)

solve_backtracking(board, stats)

print("Solved!")
print("Nodes:", stats.nodes)
print("Backtracks:", stats.backtracks)

print_board(board)

def solve_puzzle(puzzle):

    board = puzzle.copy()

    stats = Stats()

    solve_backtracking(board, stats)

    return board, stats

def evaluate_baseline(dataset, n=10):

    results = []

    for i in range(n):

        puzzle, solution = dataset[i]

        board, stats = solve_puzzle(puzzle)

        results.append({

            "nodes": stats.nodes,

            "backtracks": stats.backtracks

        })

    return results

def solve_puzzle(puzzle):

    stats = Stats()

    # convert safely: tensor → numpy → reshape
    board = puzzle.detach().cpu().numpy().copy()
    board = board.reshape(9, 9)

    solve_backtracking(board, stats)

    return board, stats

def to_board(x):

    if hasattr(x, "detach"):
        x = x.detach().cpu().numpy()
    else:
        x = np.array(x)

    return x.reshape(9, 9)


def solve_puzzle(puzzle):

    stats = Stats()

    board = to_board(puzzle)

    solve_backtracking(board, stats)

    return board, stats


def evaluate_baseline(dataset, n=5):

    results = []

    for i in range(n):

        puzzle, solution = dataset[i]

        board, stats = solve_puzzle(puzzle)

        results.append({
            "nodes": stats.nodes,
            "backtracks": stats.backtracks
        })

    return results

results = evaluate_baseline(dataset, n=5)

for i, r in enumerate(results):

    print(f"Puzzle {i}")

    print("Nodes:", r["nodes"])

    print("Backtracks:", r["backtracks"])

    print("-" * 30)

nodes = [r["nodes"] for r in results]

plt.plot(nodes)

plt.title("Baseline Solver Complexity")

plt.ylabel("Nodes explored")

plt.xlabel("Puzzle")

plt.show()

baseline_stats = evaluate_baseline(dataset, n=50)

np.save("results/baseline.npy", baseline_stats)

print("Saved baseline results.")

def get_cell_probs(board):

    model.eval()

    with torch.no_grad():

        probs = predict_probabilities(board)

    # reshape: (81, 9)
    return probs

def get_ranked_digits(cell_probs):

    # cell_probs: shape (9,)
    ranking = np.argsort(cell_probs)[::-1]

    return (ranking + 1).tolist()

def cell_index(row, col):

    return row * 9 + col

def get_ordered_digits(board, row, col):

    probs = get_cell_probs(board)

    idx = cell_index(row, col)

    cell_probs = probs[idx]

    ranked = get_ranked_digits(cell_probs)

    return ranked

def solve_backtracking_neural(board, stats):

    stats.nodes += 1

    empty = find_empty(board)

    if empty is None:

        return True

    row, col = empty

    # 🔥 NEURAL GUIDANCE HERE
    ordered_nums = get_ordered_digits(board, row, col)

    for num in ordered_nums:

        if is_valid(board, row, col, num):

            board[row][col] = num

            if solve_backtracking_neural(board, stats):

                return True

            board[row][col] = 0

            stats.backtracks += 1

    return False

puzzle, solution = dataset[0]

board = to_board(puzzle)

stats = Stats()

solve_backtracking_neural(board, stats)

print("Solved!")
print("Nodes:", stats.nodes)
print("Backtracks:", stats.backtracks)

print_board(board)

def compare_one(puzzle):

    # baseline
    b1 = to_board(puzzle)
    s1 = Stats()
    solve_backtracking(b1, s1)

    # neural
    b2 = to_board(puzzle)
    s2 = Stats()
    solve_backtracking_neural(b2, s2)

    return {
        "baseline_nodes": s1.nodes,
        "neural_nodes": s2.nodes,
        "baseline_backtracks": s1.backtracks,
        "neural_backtracks": s2.backtracks
    }

results = compare_one(dataset[0][0])

print("Baseline nodes :", results["baseline_nodes"])

print("Neural nodes   :", results["neural_nodes"])

print("Backtracks ↓   :", results["neural_backtracks"])

def batch_compare(dataset, n=10):

    out = []

    for i in range(n):

        r = compare_one(dataset[i][0])

        out.append(r)

    return out

res = batch_compare(dataset, n=10)

baseline = [r["baseline_nodes"] for r in res]

neural = [r["neural_nodes"] for r in res]

plt.plot(baseline, label="Baseline")

plt.plot(neural, label="Neural Guided")

plt.legend()

plt.title("Search Space Reduction")

plt.show()

import time

def run_single_comparison(puzzle):

    # baseline
    b1 = to_board(puzzle)
    s1 = Stats()

    t0 = time.time()
    solve_backtracking(b1, s1)
    t1 = time.time()

    # neural
    b2 = to_board(puzzle)
    s2 = Stats()

    t2 = time.time()
    solve_backtracking_neural(b2, s2)
    t3 = time.time()

    return {
        "baseline_nodes": s1.nodes,
        "neural_nodes": s2.nodes,

        "baseline_backtracks": s1.backtracks,
        "neural_backtracks": s2.backtracks,

        "baseline_time": t1 - t0,
        "neural_time": t3 - t2
    }

def benchmark(dataset, n=50):

    results = []

    for i in tqdm(range(n)):

        puzzle, _ = dataset[i]

        r = run_single_comparison(puzzle)

        results.append(r)

    return results

results = benchmark(dataset, n=30)

print("Done benchmarking.")

df = pd.DataFrame(results)

df.head()

summary = df.describe()

summary

df["node_speedup"] = df["baseline_nodes"] / df["neural_nodes"]

df["time_speedup"] = df["baseline_time"] / df["neural_time"]

df["backtrack_reduction"] = (
    df["baseline_backtracks"] - df["neural_backtracks"]
) / df["baseline_backtracks"]

df[[
    "node_speedup",
    "time_speedup",
    "backtrack_reduction"
]].describe()

plt.figure(figsize=(10,5))

plt.plot(df["baseline_nodes"], label="Baseline")

plt.plot(df["neural_nodes"], label="Neural Guided")

plt.legend()

plt.title("Nodes Explored Comparison")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["node_speedup"], bins=20, kde=True)

plt.title("Node Speedup Distribution")

plt.show()

plt.figure(figsize=(10,5))

plt.plot(df["baseline_time"], label="Baseline")

plt.plot(df["neural_time"], label="Neural Guided")

plt.legend()

plt.title("Runtime Comparison")

plt.show()

report = {

    "avg_node_speedup": df["node_speedup"].mean(),

    "median_node_speedup": df["node_speedup"].median(),

    "avg_time_speedup": df["time_speedup"].mean(),

    "avg_backtrack_reduction": df["backtrack_reduction"].mean()

}

report

import requests

def call_openrouter(prompt, model="openrouter/free"):

    headers = {

        "Authorization": f"Bearer {OPENROUTER_API_KEY}",

        "Content-Type": "application/json"

    }

    data = {

        "model": model,

        "messages": [

            {"role": "system", "content": "You are a Sudoku expert."},

            {"role": "user", "content": prompt}

        ]

    }

    response = requests.post(

        "https://openrouter.ai/api/v1/chat/completions",

        headers=headers,

        json=data

    )

    return response.json()["choices"][0]["message"]["content"]

def board_to_text(board):

    lines = []

    for r in range(9):

        row = []

        for c in range(9):

            val = board[r][c]

            row.append(str(val))

        lines.append(" ".join(row))

    return "\n".join(lines)

def build_prompt(board, row, col):

    grid = board_to_text(board)

    return f"""

You are solving a Sudoku.

Grid (0 = empty):

{grid}

We are filling cell ({row},{col}).

Return digits 1-9 ranked from most to least likely.

Only return a list like:

[5,3,1,9, ... ,2]

No explanation.

"""

import ast

def parse_llm_output(text):

    try:

        return ast.literal_eval(text)

    except:

        # fallback safe parse

        nums = [int(x) for x in text if x.isdigit()]

        return nums[:9]

def get_llm_ranking(board, row, col):

    prompt = build_prompt(board, row, col)

    response = call_openrouter(prompt)

    ranking = parse_llm_output(response)

    return ranking

def is_uncertain(probs, threshold=0.4):

    top2 = np.sort(probs)[-2:]

    gap = top2[1] - top2[0]

    return gap < threshold

def hybrid_rank(board, row, col):

    probs = get_cell_probs(board)

    idx = cell_index(row, col)

    cell_probs = probs[idx]

    # neural ranking
    neural_rank = get_ranked_digits(cell_probs)

    # uncertainty check
    if is_uncertain(cell_probs):

        try:

            llm_rank = get_llm_ranking(board, row, col)

            return llm_rank

        except:

            return neural_rank

    return neural_rank

def solve_backtracking_hybrid(board, stats):

    stats.nodes += 1

    empty = find_empty(board)

    if empty is None:

        return True

    row, col = empty

    ordered = hybrid_rank(board, row, col)

    for num in ordered:

        if is_valid(board, row, col, num):

            board[row][col] = num

            if solve_backtracking_hybrid(board, stats):

                return True

            board[row][col] = 0

            stats.backtracks += 1

    return False

puzzle, solution = dataset[0]

board = to_board(puzzle)

stats = Stats()

solve_backtracking_hybrid(board, stats)

print("Solved!")

print("Nodes:", stats.nodes)

print("Backtracks:", stats.backtracks)

print_board(board)

def compare_all(puzzle):

    b = to_board(puzzle)

    # baseline
    b1 = b.copy()
    s1 = Stats()
    solve_backtracking(b1, s1)

    # neural
    b2 = b.copy()
    s2 = Stats()
    solve_backtracking_neural(b2, s2)

    # hybrid
    b3 = b.copy()
    s3 = Stats()
    solve_backtracking_hybrid(b3, s3)

    return {
        "baseline": s1.nodes,
        "neural": s2.nodes,
        "hybrid": s3.nodes
    }

res = compare_all(dataset[0][0])

print(res)

labels = list(res.keys())

values = list(res.values())

plt.bar(labels, values)

plt.title("Baseline vs Neural vs Hybrid")

plt.ylabel("Nodes Explored")

plt.show()

